### ISSUE TITLE
[Meta] Publish mobile roadmap on w3.org

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#142]
Goal is to publish the September version of the mobile roadmap onto W3.org and create a blog post

- [x] Sync up with Comm Team
- [x] Create published version in [`https://www.w3.org/2017/12/web-roadmaps/mobile/`](https://www.w3.org/2017/12/web-roadmaps/mobile/)
- [x] Create "Latest link", for instance [`https://www.w3.org/Mobile/roadmap/`](https://www.w3.org/Mobile/roadmap/).
- [x] Add the Chinese translation
- [x] Draft blog post for home page news (and acknowledging the project is funded by Beihang University)
- [x] Add links between English and Chinese versions, e.g. in the footer of each page (Ideally, this part will be automated later on)

**Comment by tidoust** [comment]
Closing this meta-issue, roadmap was published in English and Chinese this week:
https://www.w3.org/2018/01/web-roadmaps/mobile/
https://www.w3.org/Mobile/roadmap/
