### ISSUE TITLE
April snapshot of Mobile roadmap

### ISSUE THREAD

**Issue by tidoust** [w3c/web-roadmaps#213]
Goal is to publish a new snapshot of the Mobile roadmap by 25 April 2018. Some things that need to be done:

- [x] #13 Display implementation info on mobile Web browsers
- [x] #122 Create an about page
- [x] #128 Report implementation provenance information
- [x] #143 Mechanism to filter browsers in implementations column
- [x] #211 Visual clue when implementation is behind a flag or requires a prefix
- [x] #212 Heights of maturity icons
- [x] #220 Fix Chrome Platform status data processing
- [x] #184 Make sure accessibility content is appropriate
- [x] Prepare a human-friendly "What's new" page that describes main changes since last version
- [x] Make sure that the Chinese version is up-to-date

**Comment by xfq** [comment]
I just updated the Chinese version. It's interesting to see the name of some specs changed to add or remove the level, e.g., [1](https://github.com/w3c/web-roadmaps/commit/65e8162bda7783064bd4a9e6303e3aa3fed06a3c#diff-b6c8a855372ce2e134ec54549feb287cL136), [2](https://github.com/w3c/web-roadmaps/commit/65e8162bda7783064bd4a9e6303e3aa3fed06a3c#diff-b6c8a855372ce2e134ec54549feb287cL145), [3](https://github.com/w3c/web-roadmaps/commit/65e8162bda7783064bd4a9e6303e3aa3fed06a3c#diff-b6c8a855372ce2e134ec54549feb287cL156), [4](https://github.com/w3c/web-roadmaps/commit/65e8162bda7783064bd4a9e6303e3aa3fed06a3c#diff-b6c8a855372ce2e134ec54549feb287cL173).

Maybe it's because the spec names in `tr.rdf` and the names returned by W3C API are different.

**Comment by tidoust** [comment]
> Maybe it's because the spec names in tr.rdf and the names returned by W3C API are different.

Yes, I do not exactly know what triggers the difference (my understanding is that `tr.rdf` is generated from the same database), but the new titles seem correct...

**Comment by tidoust** [comment]
Note I unchecked "Make sure that the Chinese version is up-to-date" because the About page I just prepared will have to be translated once merged.

I also added the Chrome Platform Status data bug to the list of issues to solve before publishing a snapshot. Never good to publish data we know may be incorrect...

**Comment by xfq** [comment]
I have updated the Chinese version to match the latest English version. One remaining issue is the localization of the date:

https://github.com/w3c/web-roadmaps/commit/01d81e58f4a19a8738d2ecdac692f2d4e14bba93#diff-2b0256e7169e074ea636d8ad1f0ddbf2R786

It should use `zh-CN` in the Chinese version. (Although `cmn-Hans` is more accurate, it isn't supported in the browsers I tested.)

**Comment by tidoust** [comment]
That's a good point. I used `toLocaleDateString` to generate the date precisely for that purpose, but forgot to use the language of the underlying page as parameter to the call.

Now, trouble is it only seems to work in a "real" browser. JSDOM, used to generate the pages in batch, does not support `zh-CN` on my computer as far as I can tell :(

That said, am I right to think that the correct way to represent "April 2018" in Chinese would be "2018年4月"? Or would you expect something else? If that's the right output, I'll hardcode the rule for Chinese.

**Comment by xfq** [comment]
Right, "2018年4月" is "April 2018" in Chinese.

Besides hardcoding the rule, another option might be using the `DateTimeFormat` object from [intl](https://www.npmjs.com/package/intl).

**Comment by tidoust** [comment]
Although not really advertized yet, the [April 2018 version](https://www.w3.org/2018/04/web-roadmaps/mobile/) of the mobile roadmap has been released. Closing this meta-issue accordingly.
