### ISSUE TITLE
New specs in the mobile roadmap

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#51]
Some candidates:

## WICG

- [x] [Visual Viewport API](https://github.com/WICG/ViewportAPI) (see #55)
- [x] [Web Packaging](https://github.com/WICG/webpackage) (see #57)

## WHATWG

- [x] [Storage](https://storage.spec.whatwg.org/) (see #58)

## Other groups

- [x] [WebAssembly](http://webassembly.org/) (see #56)
- [x] [Intersection Observer](https://w3c.github.io/IntersectionObserver/) (useful for infinite scrolling, which is particularly relevant on mobile devices) (see #61)
- [x] [Device Memory](https://github.com/w3c/device-memory) and [HTTP Client Hints](http://httpwg.org/http-extensions/client-hints.html) (Performance and Tuning, or Device Adaptation?) (see #63)

**Comment by tidoust** [comment]
Device Memory is an interesting one. I would put it in device adaptation. We should mention it in relation to [HTTP Client Hints](http://httpwg.org/http-extensions/client-hints.html) (that is, we should mention HTTP Client Hints as well)

**Comment by tidoust** [comment]
Closing this issue as all specs added to the latest version of the roadmap. We'll no doubt find more specs to add but I suggest creating individual issues from now on.
