### ISSUE TITLE
[mobile] Publish September 2020 snapshot

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#510]
- [x] Add the Chinese translation
- [x] Create published version in https://www.w3.org/2020/09/web-roadmaps/mobile/
- [x] Update https://www.w3.org/Mobile/roadmap/
- [x] Draft blog post for home page news

**Comment by tidoust** [comment]
@xfq, just published version in https://www.w3.org/2020/09/web-roadmaps/mobile/
All seems fine. Could you have a look and let me know if you spot something weird?

**Comment by xfq** [comment]
Thank you so much!

I updated some Chinese translations (in both git and cvs). I think it's ready to go now.
